config/routes.rb
Rails.application.routes.draw do
  
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  root 'movies#index'
  

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  searchkick
  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy

  devise :omniauthable, :omniauth_providers => [:google_oauth2]

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20]
        )
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def search
    if params[:search].present?
      @movies = Movie.search(params[:search])
    else
      @movies = Movie.all
    end
  end

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :director, :rating, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie 
  before_action :authenticate_user!
  
  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    if @review.save
      redirect_to @movie
    else
      render 'new'
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController   
    
  def google_oauth2
     
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "imovie", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "新增電影", new_movie_path, class: "active" %></li>
          <li><%= link_to "帳戶設定", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "註冊", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "登入", new_user_session_path, class: "active" %></li>
          <li>
            <%= link_to "使用Google帳號登入", user_omniauth_authorize_path(:google_oauth2) %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>imovie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
  <%= yield %>
  </div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :名稱 %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :簡介 %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :片長 %><br>
    <%= f.text_field :movie_length %>
  </div>
  <div class="field">
    <%= f.label :導演 %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :分級 %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :宣傳海報 %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>編輯文章</h1>

<%= render 'form' %>

<%= link_to '上一頁', @movie %> |
<%= link_to '回首頁', movies_path %>

app/views/movies/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>
​
  <% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>您喜愛的電影評論</h1>
    <p>最新的電影評論盡在imovie</p>
    <p><%= link_to "立即註冊", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
    </div>
  <% end %>
​
  <div class="row">
    <div class="col-sm-9 col-lg-8 col-lg-offset-2">
      <%= form_tag search_movies_path , :method => :get, :class => "movies-search-form" do %>
        <div class="input-group">
          <input type="text" class="form-control input-lg" name="q" value="<%= params[:q] %>" placeholder="搜尋電影關鍵字...">
​
          <span class="input-group-btn">
            <button type="submit" class="btn btn-default btn-lg">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
        </div>
      <% end %>
​
    <br>
    </br>
​
  </div>
    <div class="row">
      <% @movies.each do |movie| %>
        <div class="col-sm-6 col-md-3">
           <div class="thumbnail">
            <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
           </div>
        </div>
      <% end %>
    </div>
</body>
</html>

app/views/movies/new.html.erb
<h1>新增電影</h1>

<%= render 'form' %>

<%= link_to '上一頁', movies_path %>

app/views/movies/search.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
      </div>
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
         <%= image_tag @movie.image.url(:medium) %>
         <div class="star-rating" data-score= <%= @avg_review %> ></div>
         <em><%= "#{@reviews.length} reviews" %></em>
         <div class="table-responsive">
           <table class="table">
             <tbody>

               <tr>
                 <td><strong>名&nbsp;稱:</strong></td>
                 <td><%= @movie.title %></td>
               </tr>
               <tr>
                 <td><strong>簡&nbsp;介:</strong></td>
                 <td><%= @movie.description %></td>
               </tr>
               <tr>
                  <td><strong>片&nbsp;長:</strong></td>
                  <td><%= @movie.movie_length %></td>
               </tr>
               <tr>
                 <td><strong>導&nbsp;演:</strong></td>
                 <td><%= @movie.director %></td>
               </tr>
               <tr>
                 <td><strong>分&nbsp;級:</strong></td>
                 <td><%= @movie.rating %></td>
               </tr>
             </tbody>
           </table><%= link_to "新增評論", new_movie_review_path(@movie) %>
         </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @movie.title %></h1>
        <p><%= @movie.description %></p>

        <% if @reviews.blank? %>
          <h3>目前沒有評論</h3>
          <%= link_to "立即新增評論",new_movie_review_path(@movie), class:"btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to '編輯', edit_movie_path(@movie) %> |
<%= link_to '回首頁', movies_path %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :評論 %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>修改評論</h1>

<%= render 'form' %>

<%= link_to '上一頁', movie_path(@movie) %>

app/views/reviews/new.html.erb
<h1>發表評論</h1>

<%= render 'form' %>

<%= link_to '上一頁', movie_path(@movie) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
	<strong>User</strong>
	<%= @review.user.email %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>